#!/usr/bin/python

import sys

arguments = sys.stdin.read().split()

if len(arguments) == 4:
    newref, newsha, oldref, oldsha = arguments
else:
    sys.exit(0)

safe_branches = ['develop', 'pilot']

for branch in safe_branches:
    if oldref == 'refs/heads/' + branch:
        sys.stdin = open('/dev/tty')
        confirm = raw_input('Are you sure you want to push %s? [y/N] ' % branch)
        if confirm.strip().lower().startswith('y'):
            sys.exit(0)
        else:
            sys.exit(1)
