#!/usr/bin/python

import sys, re
from subprocess import check_output as cmd

def main():
    commit_message_file = sys.argv[1]
    branch_path = cmd(['git', 'symbolic-ref', '-q', 'HEAD']).strip() #refs/heads/...
    branch_name = branch_path.split('/')[-1]
    issue_number = findIssueNumber(branch_path)
    commit_message = readFile(commit_message_file)
    first_line = commit_message.splitlines() [0]
    
    if not first_line:
        message = branch_name + ': '
        writeFile(commit_message_file, message + commit_message)

def writeFile(path, text):
    with open(path, 'w') as f:
        return f.write(text)


if __name__ == '__main__': main()

