#!/usr/bin/python

import sys, re
from subprocess import check_output as cmd

BRANCH_STRUCTURE_REGEX = re.compile(
    'refs/heads/([^/]+)/.*/([^_]+)(?:[^#]*#(\S+))?'
)

def main():
    commit_message_file = sys.argv[1]
    commit_message = readFile(commit_message_file)
    first_line = commit_message.splitlines()[0]

    if not first_line:
        try:
            branch_path = cmd([
                'git',
                'symbolic-ref',
                '-q',
                'HEAD'
            ]).strip() #refs/heads/...
        except:
            sys.exit(0)

        match = BRANCH_STRUCTURE_REGEX.search(branch_path)

        if match:

            branc_type, component, issue_number = match.groups()
            message = '%s(%s):' % (branc_type, component.capitalize())

            if issue_number:
                message += '\n\nref: ' + issue_number

            writeFile(commit_message_file, message + commit_message)

def readFile(path):
    with open(path) as f:
        return f.read()

def writeFile(path, text):
    with open(path, 'w') as f:
        return f.write(text)

if __name__ == '__main__': main()

